//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VibExchange.Areas.RemoteAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlarm
    {
        public tblAlarm()
        {
            this.tblMeasurementSetup_Benstone = new HashSet<tblMeasurementSetup_Benstone>();
        }
    
        public int AlarmID { get; set; }
        public string AlarmName { get; set; }
        public string AlarmType { get; set; }
        public double HighValue { get; set; }
        public double LowValue { get; set; }
    
        public virtual ICollection<tblMeasurementSetup_Benstone> tblMeasurementSetup_Benstone { get; set; }
    }
}
