//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VibExchange.Areas.RemoteAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBearing
    {
        public int BearingID { get; set; }
        public string BearingMake { get; set; }
        public string BearingModel { get; set; }
        public double InnerDia { get; set; }
        public double OuterDia { get; set; }
        public double ContactAngel { get; set; }
        public double RollingDia { get; set; }
        public int NoOfRollingElement { get; set; }
        public double Balls { get; set; }
        public double FTF { get; set; }
        public double BSF { get; set; }
        public double BPFO { get; set; }
        public double BPFI { get; set; }
    }
}
