//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VibExchange.Areas.RemoteAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFaultFrequency
    {
        public int FrequencyID { get; set; }
        public string FrequencyName { get; set; }
        public double FrequencyValue { get; set; }
        public int PointID { get; set; }
    }
}
