//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VibExchange.Areas.RemoteAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFileData
    {
        public int FileID { get; set; }
        public string UserID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string FileFormate { get; set; }
        public string InstrumentUsed { get; set; }
        public Nullable<int> NoOfMachines { get; set; }
        public Nullable<int> NoOfPoints { get; set; }
        public string AnalysisMethod { get; set; }
        public string FilePath { get; set; }
        public string Description { get; set; }
        public System.DateTime DateOfUpload { get; set; }
    }
}
