//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VibExchange.Areas.RemoteAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJob
    {
        public int JobID { get; set; }
        public string JobTitle { get; set; }
        public string JobCategory { get; set; }
        public string Description { get; set; }
        public string ExperienceRequired { get; set; }
    }
}
