//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VibExchange.Areas.RemoteAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMeasurementSetup_Kohtect
    {
        public int SetupID { get; set; }
        public int FileID { get; set; }
        public Nullable<int> AlarmID { get; set; }
        public Nullable<int> Channel1 { get; set; }
        public Nullable<int> SelectRadio1 { get; set; }
        public Nullable<int> EVFrequency { get; set; }
        public Nullable<int> Channel2 { get; set; }
        public Nullable<int> SelectRadio2 { get; set; }
        public Nullable<int> SpectrumLineNo { get; set; }
        public Nullable<int> WindowType { get; set; }
        public Nullable<int> Fmin { get; set; }
        public Nullable<int> Fmax { get; set; }
        public Nullable<int> TriggerMode { get; set; }
        public Nullable<int> AvgMode { get; set; }
        public string N { get; set; }
        public string Comment { get; set; }
    }
}
