//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VibExchange.Areas.RemoteAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMeasure_Benstone
    {
        public tblMeasure_Benstone()
        {
            this.tblMeasurementSetup_Benstone = new HashSet<tblMeasurementSetup_Benstone>();
        }
    
        public int MeasureID { get; set; }
        public int FileID { get; set; }
        public bool OverAcc { get; set; }
        public bool OverVel { get; set; }
        public bool OverDisp { get; set; }
        public bool OverBear { get; set; }
        public bool TimeWaveForm { get; set; }
        public bool PowerSpectrum { get; set; }
        public bool DemodulateSpectrum { get; set; }
        public bool Temprature { get; set; }
        public bool ProcessParameter { get; set; }
        public bool CrestFacture { get; set; }
        public bool OrderTrace { get; set; }
        public bool Cepstrum { get; set; }
        public int CalcMeasure { get; set; }
    
        public virtual ICollection<tblMeasurementSetup_Benstone> tblMeasurementSetup_Benstone { get; set; }
    }
}
