//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VibExchange.Areas.RemoteAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlant
    {
        public int PlantID { get; set; }
        public string PlantName { get; set; }
        public string Category { get; set; }
        public string PlantDetail { get; set; }
        public int FileID { get; set; }
        public string NodeType { get; set; }
    }
}
