//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VibExchange.Areas.RemoteAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPointData_Kohtect
    {
        public int DataID { get; set; }
        public int PointID { get; set; }
        public int SetupID { get; set; }
        public System.DateTime MeasureTime { get; set; }
        public int FileID { get; set; }
        public string OverallValue { get; set; }
        public string OverallUnit { get; set; }
        public string Chnl1Time_X { get; set; }
        public string Chnl1Time_Y { get; set; }
        public string Chnl2Time_X { get; set; }
        public string Chnl2Time_Y { get; set; }
        public string Chnl1FFT_X { get; set; }
        public string Chnl1FFT_Y { get; set; }
        public string Chnl2FFT_X { get; set; }
        public string Chnl2FFT_Y { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
