//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VibExchange.Areas.RemoteAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSensor
    {
        public int SensorID { get; set; }
        public string SensorName { get; set; }
        public string SensorType { get; set; }
        public Nullable<int> Sensitivity_Ch1 { get; set; }
        public Nullable<int> Sensitivity_Ch2 { get; set; }
        public Nullable<int> Sensitivity_Ch3 { get; set; }
        public Nullable<int> Sensitivity_Ch4 { get; set; }
        public string SensorUnit { get; set; }
        public string SensorDirection { get; set; }
        public bool SensorICP { get; set; }
        public string SensorOffset { get; set; }
        public Nullable<int> InputRange { get; set; }
    }
}
